version: '3.7'

services:
  ri_ml-interview:
    image: ri_ml-interview
    container_name: ri_ml-interview
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=0
    tty: true
    ports:
      - 8003:5000

networks:
  default:
    external:
      name: ri_network
